<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2007 sp2 (http://www.altova.com)-->
<Manifest CSUVersion="1.0" xsi:noNamespaceSchemaLocation="CSUManifest.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<UpdateID>update12</UpdateID>
	<OwningChannel>AdobeApplicationManager-1.0</OwningChannel>
	<AAMInfo>
		<Channel>
			<DisplayName>Adobe Application Manager</DisplayName>
		</Channel>
	</AAMInfo>
  <DisplayName default="en_US">
    <ar_AE>Adobe® Application Manager® Self Update</ar_AE>
    <bg_BG>Adobe® Application Manager® Self Update</bg_BG>
    <cs_CZ>Adobe® Application Manager® Self Update</cs_CZ>
    <da_DK>Adobe® Application Manager® Self Update</da_DK>
    <de_DE>Adobe® Application Manager® Self Update</de_DE>
    <el_GR>Adobe® Application Manager® Self Update</el_GR>
    <en_US>Adobe® Application Manager® Self Update</en_US>
    <es_ES>Adobe® Application Manager® Self Update</es_ES>
    <et_EE>Adobe® Application Manager® Self Update</et_EE>
    <fi_FI>Adobe® Application Manager® Self Update</fi_FI>
    <fr_FR>Adobe® Application Manager® Self Update</fr_FR>
    <he_IL>Adobe® Application Manager® Self Update</he_IL>
    <hr_HR>Adobe® Application Manager® Self Update</hr_HR>
    <hu_HU>Adobe® Application Manager® Self Update</hu_HU>
    <it_IT>Adobe® Application Manager® Self Update</it_IT>
    <ja_JP>Adobe® Application Manager® Self アップデート</ja_JP>
    <ko_KR>Adobe® Application Manager® Self 업데이트</ko_KR>
    <lt_LT>Adobe® Application Manager® Self Update</lt_LT>
    <lv_LV>Adobe® Application Manager® Self Update</lv_LV>
    <nb_NO>Adobe® Application Manager® Self Update</nb_NO>
    <nl_NL>Adobe® Application Manager® Self Update</nl_NL>
    <pl_PL>Adobe® Application Manager® Self Update</pl_PL>
    <pt_BR>Adobe® Application Manager® Self Update</pt_BR>
    <ro_RO>Adobe® Application Manager® Self Update</ro_RO>
    <ru_RU>Adobe® Application Manager® Self Update</ru_RU>
    <sk_SK>Adobe® Application Manager® Self Update</sk_SK>
    <sl_SI>Adobe® Application Manager® Self Update</sl_SI>
    <sv_SE>Adobe® Application Manager® Self Update</sv_SE>
    <tr_TR>Adobe® Application Manager® Self Update</tr_TR>
    <uk_UA>Adobe® Application Manager® Self Update</uk_UA>
    <zh_CN>Adobe® Application Manager® Self 更新</zh_CN>
    <zh_TW>Adobe® Application Manager® Self 更新</zh_TW>
  </DisplayName>
  <Description default="en_US">
    <ar_AE>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</ar_AE>
    <bg_BG>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</bg_BG>
    <cs_CZ>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</cs_CZ>
    <da_DK>Adobe® Application Manager® DMG Update installerer programrettelsen Adobe Application ManagerApplication Manager  oven på alle tidligere versioner af Application Manager</da_DK>
    <de_DE>Mit dem Adobe® Application Manager® -DMG Update wird eine bereits vorhandene Version von Application Manager  mit dem Adobe Application Manager -Patch aktualisiert</de_DE>
    <el_GR>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</el_GR>
    <en_US>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</en_US>
    <es_ES>Adobe® Application Manager® DMG Update instalará el parche para Adobe Application Manager  por encima de cualquier versión anterior de Application Manager</es_ES>
    <et_EE>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</et_EE>
    <fi_FI>Adobe® Application Manager® DMG Update asentaa Adobe Application Manager  -korjaustiedoston minkä tahansa Application Manager  -ohjelman aiemman version päälle</fi_FI>
    <fr_FR>"Adobe® Application Manager® DMG Update permet l'installation du correctif Adobe Application Manager  sur toute version précédente d'Application Manager</fr_FR>
    <he_IL>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</he_IL>
    <hr_HR>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</hr_HR>
    <hu_HU>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</hu_HU>
    <it_IT>Adobe® Application Manager® DMG Update eseguirà l’applicazione della patch Adobe Application Manager  a qualsiasi versione precedente di Application Manager  per implementare le correzioni di alcuni errori nei moduli</it_IT>
    <ja_JP>Adobe® Application Manager®  DMG アップデートは、Adobe Application Manager  パッチを以前の任意のバージョンの Application Manager  に上書きインストールします</ja_JP>
    <ko_KR>Adobe® Application Manager®  DMG 업데이트는 이전 버전의 Application Manager 에 Adobe Application Manager  패치를 설치합니다</ko_KR>
    <lt_LT>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</lt_LT>
    <lv_LV>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</lv_LV>
    <nb_NO>Adobe® Application Manager® DMG Update innebærer at oppdateringen Adobe Application Manager  installeres over en tidligere versjon av Application Manager</nb_NO>
    <nl_NL>Met de Adobe® Application Manager® DMG Update wordt de patch Adobe Application Manager  geïnstalleerd boven op een eerdere versie van Application Manager</nl_NL>
    <pl_PL>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</pl_PL>
    <pt_BR>A Adobe® Application Manager® DMG Update instalará uma parte do Adobe Application Manager  sobre qualquer versão prévia do Application Manager</pt_BR>
    <ro_RO>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</ro_RO>
    <ru_RU>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</ru_RU>
    <sk_SK>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</sk_SK>
    <sl_SI>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</sl_SI>
    <sv_SE>Adobe® Application Manager® DMG Update installerar korrigeringsfilen för Adobe Application Manager  över eventuell tidigare version av Application Manager</sv_SE>
    <tr_TR>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</tr_TR>
    <uk_UA>The Adobe® Application Manager® DMG Update will install the Adobe Application Manager  patch on top of any previous version of Application Manager</uk_UA>
    <zh_CN>Adobe® Application Manager® DMG 更新”将在早期版本的 Application Manager  基础上安装 Adobe Application Manager  修补程序</zh_CN>
    <zh_TW>“Adobe® Application Manager® DMG 更新”將在以前版本的 Application Manager  基礎上安裝 Adobe Application Manager  修補程式</zh_TW>
  </Description>
  <AffectedChannels>
    <ChannelID>AdobeApplicationManager-1.0</ChannelID>
  </AffectedChannels>
<Dependency>
</Dependency>		
	<Notify>0</Notify>
	<WhenApply>2</WhenApply>
	<InstallFiles>
		<File>
			<Name>SelfUpdate.zip</Name>
			<Type>1</Type>
     			<ExecutableName> set-up.exe</ExecutableName>
			<SilentExecutableArgs>--action=update</SilentExecutableArgs>
			<Size>214771</Size>
		</File>
	</InstallFiles>
	<NeedsReboot>false</NeedsReboot>
</Manifest>
